#!/bin/sh

RUNAS=root
MINECRAFTHOME=$(dirname $0)

start() {
  if screen -list | grep -q "minecraft"; then
    echo 'Server already running'
    return 1
  fi
  echo 'Starting minecraft server…' >&2
  su -c $MINECRAFTHOME/start $RUNAS
  echo 'Server started'
}

stop() {
  if ! su -c 'screen -list | grep -q "minecraft"' $RUNAS; then
    echo 'Server not running'
    exit 1
  fi
  echo 'Stopping minecraft server…'
  su -c "$MINECRAFTHOME/stop" $RUNAS
  echo 'Server stopped'
}

restart() {
  if ! su -c 'screen -list | grep -q "minecraft"' $RUNAS; then
    echo 'Server not running'
    start
    exit 1
  fi
  su -c "$MINECRAFTHOMErestart" $RUNAS
}


case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    restart
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
esac
