#!/bin/sh

RUNAS=root
MINECRAFTHOME="$( dirname $(realpath $0))"

SCREEN=$(head -n 1 $MINECRAFTHOME/screenname.txt)


start() {
  if su -c "screen -list | grep -q \"$SCREEN\""  $RUNAS; then
    echo 'Server already running'
    return 1
  fi
  echo 'Starting minecraft server…' >&2
  su -c $MINECRAFTHOME/start $RUNAS
  echo 'Server started'
}

stop() {
  if ! su -c "screen -list | grep -q \"$SCREEN\""  $RUNAS; then
    echo 'Server not running'
    exit 1
  fi
  echo 'Stopping minecraft server…'
  su -c "$MINECRAFTHOME/stop" $RUNAS
  echo 'Server stopped'
}

restart() {
  if ! su -c "screen -list | grep -q \"$SCREEN\""  $RUNAS; then
    echo 'Server not running'
    start
    exit 1
  fi
  su -c "$MINECRAFTHOME/restart" $RUNAS
  echo 'Server restarted'
}

status() {
  if ! su -c "screen -list | grep -q \"$SCREEN\""  $RUNAS; then
    echo 'Server not running'
  else
    echo 'Server running'
  fi
}


case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    restart
    ;;
  status)
    status
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|status}"
esac
